Double-Raph/raclettenb

- Gemfile
- Gemfile.lock
- app/models/user.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20241203104738_devise_create_users.rb
- db/schema.rb
- test/models/user_test.rb
> Generated User standard model (need to custom) 
> Sign in view available (on localhost:3000)
> installed devise

- app/models/raclette.rb
- db/migrate/20241203112724_create_raclettes.rb
- test/models/raclette_test.rb
> Ajout du model Raclette et des validations.
> Create model raclette

- app/models/user.rb
added DB Schema fields 
Do we need "password" field ? 
Appears to be handled through devise (so not necessary)
> updated user model

- .gitignore
- Gemfile
- Gemfile.lock
- app/models/raclette.rb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20241203153327_create_active_storage_tables.active_storage.rb
- db/schema.rb
added my Cloudinary API key (secured through dotenv + .env file) 
modified config/environnements files 
modified storage.yml
added association on raclette.rb model 
added cloudinary gem
> added cloudinary setup

- app/models/booking.rb
- db/migrate/20241203143959_create_bookings.rb
- db/schema.rb
- test/models/booking_test.rb
création modèle bookings et validations
> create model bookings

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
> home controller et html

- config/routes.rb
Add all routes for raclettes & bookings
> raclettes & bookings routes

- app/controllers/raclettes_controller.rb
added 
edit // my_raclettes // update // destroy
with raclette_params***
> added edit update my_raclette and delete to raclette_controller

- Gemfile
- Gemfile.lock
- db/seeds.rb
> seeds upgrade

- app/views/devise/sessions/new.html.erb
removed first name / last name fields for login
> fixed log in fields

- app/views/pages/home.html.erb
> redesigned homepage

- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
corrected homepage mistakes (spelling) / and click on icon sends to homepage (navbar)
> Hotfix homepage

- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_flip_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/raclettes/index.html.erb
creating flip-card component
(work in progress)
> component flip card in progress

- app/controllers/pages_controller.rb
fixed login issues on index / show et home
> fixed login issues

- app/controllers/raclettes_controller.rb
- app/views/raclettes/edit.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
créer view edit avec formulaire édition raclette
supprimer occurrences my_raclettes
> edit raclette form

- app/controllers/pages_controller.rb
- app/controllers/raclettes_controller.rb
- app/views/pages/dashboard.html.erb
- config/routes.rb
Created : 
route for dashboard
Added 
Dashboard methods in Pages Controller
View for dashboard with "my raclette"
Fixed login issues for public show and public index
> added dashboard route / controller / view + login fixes

- app/views/pages/dashboard.html.erb
- app/views/shared/_navbar.html.erb
> fixed dashboard view

- app/controllers/bookings_controller.rb
- app/controllers/raclettes_controller.rb
- app/views/pages/dashboard.html.erb
@ab64600 
J'ai tenté un truc pour les méthodes accept et decline mais pas possible de tester sans avoir les bookings dans le dashboard, du coup on peut merge ça et je te laisserai tester ça une fois que tu auras affiché les bookings avec ?
Je t'ai ajouté les liens avec un commentaire dans la view du dashboard.
> Accept decline booking

- app/assets/stylesheets/components/_container.scss
- app/views/raclettes/show.html.erb
désolé noah, promis j'répare ca
> show enhanced, almost

- app/views/pages/home.html.erb
- app/views/raclettes/index.html.erb
> Search form style

- app/views/pages/dashboard.html.erb
Delete wasn't working properly
without confirm
fixed now
> fixed delete feature with modal on dashboard

- app/views/pages/dashboard.html.erb
du radius des images de l'amour
> sexy dashboard v2

- app/controllers/raclettes_controller.rb
> hotfix heroku create
